<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class M_blog_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get m_blog by id_blog
     */
    function get_m_blog($id_blog)
    {
        return $this->db->get_where('m_blog',array('id_blog'=>$id_blog))->row_array();
    }
    
    /*
     * Get all m_blog count
     */
    function get_all_m_blog_count()
    {
        $this->db->from('m_blog');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all m_blog
     */
    function get_all_m_blog($params = array())
    {
        $this->db->order_by('id_blog', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('m_blog')->result_array();
    }
        
    /*
     * function to add new m_blog
     */
    function add_m_blog($params)
    {
        $this->db->insert('m_blog',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update m_blog
     */
    function update_m_blog($id_blog,$params)
    {
        $this->db->where('id_blog',$id_blog);
        return $this->db->update('m_blog',$params);
    }
    
    /*
     * function to delete m_blog
     */
    function delete_m_blog($id_blog)
    {
        return $this->db->delete('m_blog',array('id_blog'=>$id_blog));
    }
}
