<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class M_promo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get m_promo by id_promo
     */
    function get_m_promo($id_promo)
    {
        return $this->db->get_where('m_promo',array('id_promo'=>$id_promo))->row_array();
    }
    
    /*
     * Get all m_promo count
     */
    function get_all_m_promo_count()
    {
        $this->db->from('m_promo');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all m_promo
     */
    function get_all_m_promo($params = array())
    {
        $this->db->order_by('id_promo', 'acs');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('m_promo')->result_array();
    }
        
    /*
     * function to add new m_promo
     */
    function add_m_promo($params)
    {
        $this->db->insert('m_promo',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update m_promo
     */
    function update_m_promo($id_promo,$params)
    {
        $this->db->where('id_promo',$id_promo);
        return $this->db->update('m_promo',$params);
    }
    
    /*
     * function to delete m_promo
     */
    function delete_m_promo($id_promo)
    {
        return $this->db->delete('m_promo',array('id_promo'=>$id_promo));
    }
}
