<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class M_user_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get m_user by id_user
     */
    function get_m_user($id_user)
    {
        return $this->db->get_where('m_users',array('id_user'=>$id_user))->row_array();
    }
    
    /*
     * Get all m_users count
     */
    function get_all_m_users_count()
    {
        $this->db->from('m_users');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all m_users
     */
    function get_all_m_users($params = array())
    {
        $this->db->order_by('id_user', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('m_users')->result_array();
    }
        
    /*
     * function to add new m_user
     */
    function add_m_user($params)
    {
        $this->db->insert('m_users',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update m_user
     */
    function update_m_user($id_user,$params)
    {
        $this->db->where('id_user',$id_user);
        return $this->db->update('m_users',$params);
    }
    
    /*
     * function to delete m_user
     */
    function delete_m_user($id_user)
    {
        return $this->db->delete('m_users',array('id_user'=>$id_user));
    }
}
